# Generated by Django 3.0.3 on 2020-07-16 21:11

from django.db import migrations, models
import django.db.models.deletion
import tracks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('T', 'Typing'), ('F', 'Face'), ('V', 'Voice'), ('S', 'Screen')], max_length=1)),
                ('blob', models.FileField(blank=True, null=True, upload_to=tracks.models.random_file_name)),
                ('data', models.TextField(blank=True)),
                ('metadata', models.TextField(blank=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('quality', models.FloatField(blank=True, default=0)),
                ('confidence', models.FloatField(blank=True, default=0)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
