# Generated by Django 3.0.3 on 2020-08-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='max_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='uses',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
