# Generated by Django 3.0.3 on 2020-04-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='academic_level',
            field=models.TextField(choices=[('C', 'College'), ('M', 'Master'), ('D', 'Doctor')], default=('C', 'College'), max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='curriculum',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
