# Generated by Django 3.0.3 on 2020-04-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200415_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
    ]
