# Generated by Django 3.0.3 on 2020-04-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200415_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tdna_id',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
