# Generated by Django 3.0.3 on 2020-04-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('users', '0005_auto_20200416_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institutions',
            field=models.ManyToManyField(to='institutions.Institution'),
        ),
    ]
