# Generated by Django 3.0.3 on 2020-04-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('users', '0006_user_institutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institutions',
            field=models.ManyToManyField(related_name='users', to='institutions.Institution'),
        ),
    ]
