# Generated by Django 3.0.3 on 2020-05-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200515_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='datetime_last_face',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='datetime_last_voice',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='datetime_last_writing',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
