# Generated by Django 3.0.3 on 2020-07-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200724_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voucher',
            field=models.TextField(blank=True),
        ),
    ]
