# Generated by Django 3.0.3 on 2020-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_academic_level',
            field=models.TextField(blank=True),
        ),
    ]
