# Generated by Django 3.0.3 on 2020-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_other_academic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_level',
            field=models.TextField(choices=[('C', 'College'), ('M', 'Master'), ('D', 'Doctor'), ('O', 'Other')], default=('C', 'College'), max_length=1),
        ),
    ]
