# Generated by Django 3.0.3 on 2020-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200813_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_level',
            field=models.TextField(choices=[('H', 'High School'), ('C', 'College'), ('M', 'Master'), ('D', 'Doctor'), ('O', 'Other')], default=('H', 'High School'), max_length=1),
        ),
    ]
