# Generated by Django 3.0.3 on 2020-10-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20201022_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_professor',
        ),
    ]
