# Generated by Django 3.0.3 on 2021-01-28 20:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institutions',
        ),
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.random_cover_name),
        ),
    ]
