version: '3'
services:
    db:
        image: 'postgres' # use latest official postgres version
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - ./database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

    web-server:
        build: ./packages/web-server
        command: python manage.py runserver 0:8000
        env_file: .env
        volumes:
            - /mnt/public:/home/app/web/public/
        expose:
            - 8000
        depends_on:
            #- db
            - elasticsearch

    # media-server:
    #     build: ./packages/media-server
    #     command: python main.py
    #     env_file: .env
    #     expose:
    #         - 8001

    face-embedding-server:
        build: ./packages/face-embedding-server
        environment:
            - FLASK_PORT=5000
        expose:
            - 5000

    voice-embedding-server:
        build: ./packages/voice-embedding-server
        environment:
            - FLASK_PORT=5001
        expose:
            - 5001

    text-embedding-server:
        build: ./packages/text-embedding-server
        environment:
            - FLASK_PORT=5002
        ports:
            - 5002:5002
        expose:
            - 5002

    elasticsearch:
        image: elasticsearch:7.8.0
        environment:
            - discovery.type=single-node
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        expose:
            - 9200
            - 9300

    nginx:
        build:
            context: ./packages/nginx
            args:
                # env_conf: nginx_prod.conf
                env_conf: nginx_qa.conf
        ports:
            - 443:443
        depends_on:
            - web-server
            # - media-server

volumes:
    elasticsearch:
        driver: local
