# Generated by Django 3.0.3 on 2020-10-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0003_auto_20201022_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='datetime_ended',
            new_name='ended_at',
        ),
    ]
