# Generated by Django 3.0.3 on 2020-05-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='journal',
            field=models.TextField(blank=True),
        ),
    ]
