# Generated by Django 3.0.3 on 2020-05-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20200521_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
