# Generated by Django 3.0.3 on 2021-02-25 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0015_auto_20201211_2302'),
        ('merits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merit',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='merit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
