# Generated by Django 3.0.3 on 2020-08-14 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20200814_1435'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentassignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='assignments.Assignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
