# Generated by Django 3.0.3 on 2020-08-14 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20200814_1435'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentassignments', '0002_auto_20200814_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Assignment'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
