# Generated by Django 3.0.3 on 2020-12-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clazzes', '0003_auto_20201211_2120'),
        ('studentassignments', '0005_auto_20201022_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='clazz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clazzes.Clazz'),
        ),
    ]
