# Generated by Django 3.0.3 on 2020-08-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentassignments', '0002_auto_20200814_1553'),
        ('documents', '0005_auto_20200625_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='studentassignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentassignments.StudentAssignment'),
        ),
    ]
