# Generated by Django 3.0.3 on 2020-08-27 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20200814_1435'),
        ('studentassignments', '0003_auto_20200814_1730'),
        ('documents', '0007_auto_20200817_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.Assignment'),
        ),
        migrations.AlterField(
            model_name='document',
            name='studentassignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentassignments.StudentAssignment'),
        ),
    ]
