# Generated by Django 3.0.3 on 2020-08-27 20:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentassignments', '0003_auto_20200814_1730'),
        ('documents', '0008_auto_20200827_1835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('studentassignment', 'user')},
        ),
    ]
