# Generated by Django 3.0.3 on 2020-09-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20200827_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pasted_chars',
            field=models.IntegerField(default=0),
        ),
    ]
