# Generated by Django 3.0.3 on 2020-10-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20201022_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='raw_data',
            field=models.TextField(blank=True),
        ),
    ]
