# Generated by Django 3.0.3 on 2020-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
