# Generated by Django 3.0.3 on 2020-11-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20201029_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='requires_screen',
            field=models.BooleanField(default=False),
        ),
    ]
