# Generated by Django 3.0.3 on 2020-12-11 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentassignments', '0006_studentassignment_clazz'),
        ('assignments', '0008_auto_20201022_1933'),
        ('documents', '0014_document_requires_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.Assignment'),
        ),
        migrations.AlterField(
            model_name='document',
            name='studentassignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentassignments.StudentAssignment'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
