# Generated by Django 3.0.3 on 2021-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20201211_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='has_template',
            field=models.BooleanField(default=False),
        ),
    ]
