# Generated by Django 3.0.3 on 2020-12-10 22:27

import clazzes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20201022_1926'),
        ('clazzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clazz',
            name='code',
            field=models.TextField(default=clazzes.models.gen_code, editable=False),
        ),
        migrations.AlterField(
            model_name='clazz',
            name='institution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
    ]
