# Generated by Django 3.0.3 on 2020-12-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clazzes', '0002_auto_20201210_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clazz',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='clazz',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
