# Generated by Django 3.0.3 on 2020-08-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='has_facial_recognition',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='has_screen_invigilation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='has_typing_cadence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='has_voice_recognition',
            field=models.BooleanField(default=True),
        ),
    ]
