# Generated by Django 3.0.3 on 2021-02-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20201230_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='msg_1000_merits',
            field=models.TextField(blank=True, default='Congratulations! You have earned 1000 points and have written an excellent amount of original work. You are doing well and are on the right track. Start thinking about how you’ll redeem your points!'),
        ),
    ]
