# Generated by Django 3.0.3 on 2020-05-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('status', models.TextField(choices=[('O', 'Open'), ('I', 'In Progress'), ('R', 'In Revision'), ('G', 'Graded')], default=('O', 'Open'), max_length=1)),
                ('grade', models.TextField(blank=True)),
                ('final_comment', models.TextField(blank=True)),
                ('datetime_due', models.DateTimeField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
