# Generated by Django 3.0.3 on 2020-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_advisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.TextField(choices=[('D', 'Draft'), ('O', 'Open'), ('I', 'In Progress'), ('R', 'In Revision'), ('G', 'Graded')], default=('D', 'Draft'), max_length=1),
        ),
    ]
